
CREATE DATABASE SalesManagementSystem;
GO

USE SalesManagementSystem;
GO

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Username NVARCHAR(50) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    Role NVARCHAR(50) NOT NULL CHECK (Role IN ('Admin', 'User'))
);
GO

-- Insert Default Admin (Password is 'admin123' hashed with SHA256)
INSERT INTO Users (Username, PasswordHash, Role) 
VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Admin');
GO

CREATE TABLE Customers (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL
);
GO

CREATE TABLE Products (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX),
    ImageUrl NVARCHAR(500),
    Price DECIMAL(18,2) NOT NULL,
    Stock INT NOT NULL,
    Vat DECIMAL(4,2) NOT NULL,
    MainCategory NVARCHAR(50) NOT NULL, 
    SubCategory NVARCHAR(50) NOT NULL,  
    Brand NVARCHAR(50) NOT NULL         
);
GO

CREATE TABLE Transactions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CustomerId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Customers(Id),
    ProductId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Products(Id),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    Quantity INT NOT NULL,
    TransactionDate DATETIME NOT NULL DEFAULT GETDATE()
);
GO