CREATE TABLE Orders (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id), 
    OrderDate DATETIME DEFAULT GETDATE(),
    TotalAmount DECIMAL(18,2)
);

CREATE TABLE OrderItems (
    Id INT PRIMARY KEY IDENTITY(1,1),
    OrderId INT FOREIGN KEY REFERENCES Orders(Id),
    ProductId INT FOREIGN KEY REFERENCES Products(Id),
    Price DECIMAL(18,2)
);