USE GestiuneVanzari;
GO

DROP TABLE IF EXISTS Tranzactii;
DROP TABLE IF EXISTS Produse;
DROP TABLE IF EXISTS Clienti;
DROP TABLE IF EXISTS Categorii;
DROP TABLE IF EXISTS Branduri;
DROP TABLE IF EXISTS Utilizatori;
GO

CREATE TABLE Utilizatori (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Username NVARCHAR(50) UNIQUE NOT NULL,
    ParolaHash NVARCHAR(255) NOT NULL, 
    Rol NVARCHAR(20) NOT NULL CHECK (Rol IN ('Admin', 'User')) 
);
GO

INSERT INTO Utilizatori (Username, ParolaHash, Rol) VALUES ('admin', 'admin123', 'Admin');
GO

CREATE TABLE Categorii (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Nume NVARCHAR(100) NOT NULL UNIQUE
);
GO

CREATE TABLE Branduri (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Nume NVARCHAR(100) NOT NULL UNIQUE
);
GO

CREATE TABLE Clienti (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Nume NVARCHAR(100) NOT NULL,
    Prenume NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL
);
GO

CREATE TABLE Produse (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Nume NVARCHAR(255) NOT NULL,
    Descriere NVARCHAR(MAX),
    ImagineUrl NVARCHAR(500),
    Pret DECIMAL(18,2) NOT NULL,
    Stoc INT NOT NULL,
    TVA DECIMAL(4,2) NOT NULL,
    CategorieId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Categorii(Id),
    BrandId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Branduri(Id)       
);
GO

CREATE TABLE Tranzactii (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    ClientId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Clienti(Id),
    ProdusId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Produse(Id),
    UtilizatorId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Utilizatori(Id), 
    Cantitate INT NOT NULL,
    DataTranzactie DATETIME NOT NULL DEFAULT GETDATE()
);
GO