CREATE TABLE OrderItems (
    Id INT PRIMARY KEY IDENTITY(1,1),
    OrderId INT FOREIGN KEY REFERENCES Orders(Id),
    ProductId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Products(Id),
    Price DECIMAL(18,2)
);